version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talk
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  backend:
    build: ../backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/talk
      SECRET_KEY: dev_secret
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data: 